# Generated by Django 4.2.7 on 2025-11-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('solicitante', 'Solicitante'), ('aprobador', 'Aprobador'), ('auditor', 'Auditor'), ('gestor', 'Gestor Documental'), ('admin', 'Admin')], default='solicitante', max_length=20),
        ),
    ]
