# Generated by Django 4.2.7 on 2025-12-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('solicitante', 'Solicitante'), ('aprobador', 'Aprobador'), ('auditor', 'Auditor'), ('gestor', 'Gestor Documental'), ('coordinador', 'Coordinador'), ('subdirector', 'Subdirector'), ('director', 'Director'), ('admin', 'Admin')], default='solicitante', max_length=20),
        ),
    ]
