# Generated by Django 4.2.7 on 2025-11-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentflow',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='tramites/'),
        ),
    ]
