# Generated by Django 4.2.7 on 2025-11-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentflow_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentflow',
            name='etapa',
            field=models.IntegerField(choices=[(1, 'Etapa 1'), (2, 'Etapa 2'), (3, 'Etapa 3'), (4, 'Etapa 4'), (5, 'Etapa 5'), (6, 'Etapa 6')], default=1),
        ),
        migrations.AlterField(
            model_name='documentflow',
            name='folio',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='documentflow',
            name='status',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
