# Generated by Django 4.2.7 on 2025-11-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentflow_etapa_alter_documentflow_folio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentflow',
            name='folio',
            field=models.CharField(default='FOL-DEFAULT', max_length=50, unique=True),
        ),
    ]
