# Generated by Django 4.2.7 on 2025-11-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentflow_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentflow',
            name='folio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
