# Generated by Django 4.2.7 on 2025-11-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentflow_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentflow',
            name='etapa',
            field=models.CharField(choices=[(1, 'Etapa 1'), (2, 'Etapa 2'), (3, 'Etapa 3'), (4, 'Etapa 4'), (5, 'Etapa 5'), (6, 'Etapa 6'), ('otro', 'Otro')], default='1', max_length=10),
        ),
    ]
