# Generated by Django 4.2.7 on 2025-12-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documentflow_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentflow',
            name='etapa',
            field=models.CharField(choices=[('becas', 'Becas'), ('calendario', 'Calendario'), ('inscripcion', 'Inscripción'), ('calificaciones', 'Calificaciones'), ('documentos', 'Documentos'), ('seguridad_social', 'Seguridad Social'), ('recursos', 'Recursos'), ('participacion', 'Participación')], default='becas', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentflow',
            name='folio',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
