# Generated by Django 4.2.7 on 2025-12-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_documentflow_etapa_alter_documentflow_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentflow',
            name='cancelado_por_estudiante',
            field=models.BooleanField(default=False, verbose_name='Cancelado por estudiante'),
        ),
        migrations.AddField(
            model_name='documentflow',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación'),
        ),
    ]
